### PR TITLE
Add plugin for atlas EZO pH

### PR DESCRIPTION
**Pull request by sebasto**
I'm looking for a water pH iot sensor since a long time, I finally found something reliable from Atlas Scientific and wrote a plugin for EspEasy in order to use this sensor easily.

I hope it will be usefull for other people.

### CODE REVIEW

**Comment by sebasto** [comment]
This pull request adds a plugin for EC measurements with Atlas scientific EC EZO and a few corrections on pH plugin.

**Comment by projectsun2** [comment]
Hello,

I get an error while compiling in line 54
invalid conversion from 'const __FlashStringHelper*' to 'int' [-fpermissive]

What can i do? Maybe you have a precompiled file for Nodemcu 4M?

**Comment by projectsun2** [comment]
The file is _P214_Atlas_EZO_pH.ino. If I change 
```
addFormCheckBox(string, F("Status LED"), F("Plugin_214_status_led"), Settings.TaskDevicePluginConfig[event->TaskIndex][1]);`
addFormSubHeader(string, F("Calibration"));
```
to 
```
addFormCheckBox(F("Status LED"), F("Plugin_214_status_led"), Settings.TaskDevicePluginConfig[event->TaskIndex][1]);
addFormSubHeader(F("Calibration"));
```
(removing "string," in every line with addFormCheckBox, addFormSubHeader, addCheckBox, addNumericBox etc.) the compilation succeeds.

**Comment by sebasto** [comment]
It's stange because I compiles on my side and there has been no new commits in EspEasy since my release.

I developped this plugin for EspEasy Mega, maybe that's the source of the problem. Which branch of EspEasy are you using ?

**Comment by projectsun2** [comment]
I compiled with source from Release mega-20180524.
It works, i get values, but i can not calibrate the sensor. Maybe you have a precompiled file for me.
easy1
easy2

**Comment by sebasto** [comment]
Hello,

Your screen capture helped a lot. 
I did not know that the standard for form handling has been modifyed in easyEsp.
I updated my plugin to follow this new standard, it should work now.

Can you try with the source code in my fork (https://github.com/sebasto/ESPEasyPluginPlayground) and confirm it works for you ?

Thank you very much,

Sébastien.

**Comment by sebasto** [comment]
I think my plugin code is OK. The thig is that it has to be used with the latest EspEasy code in the mega branch.

My fork of EspEasy was not up to date, I only syncked the playground. Now I syncked both. But here is what I think you should do to test 
- get latest code form official EspEasy repo (mega branch)
- get the playground from my fork
- copy the Atlas scientific plugins from the playground directory into your EspEasy directory
- compile

It should work (it does on my side)

Sincerely,

Sébastien.

**Pull request merged**
