### PR TITLE
Add support for digital potentiometer : _P152_MCP42010.ino

### PR DESCRIPTION
**Pull request by antibill51**
Hi.

I made a functional plugin, which corresponds to my expectations, except that ...
When I activate the plugin in device tab, I can not change the state of a GPIO anymore. I have to disable my plugin for it to work again ...

I'm using this Library : https://github.com/mensink/arduino-lib-MCP42010
Can you help me?

### CODE REVIEW

**Comment by TD-er** [comment]
You mean the GPIO's are also used for something like a switch plugin?

**Comment by antibill51** [comment]
Exactly, I need to use it with other devices, like ds18b20, hc-sr04,  switchs, and gpio basic on/off.
And if it's possible, with "Plugin 042: NeoPixel Candle"
But when I activate my plugin, other plugins do not work anymore...

**Comment by TD-er** [comment]
In this part of the code is your problem:
```c++
    case PLUGIN_WRITE:
      {
        String command = parseString(string, 1);
          MCP42010 digipot(Plugin_152_pin[0], Plugin_152_pin[1], Plugin_152_pin[2]);


         if (command == F("chambre"))
```
Regardless if the command matches, you will create an object which probably changes the state of these pins.
So you must make sure it only does that when the command matches.
That will probably fix your issue.

**Comment by antibill51** [comment]
Thanks. I try this : 

```
     case PLUGIN_WRITE:
       {
         String command = parseString(string, 1);
 
          if (command == F("chambre"))
           MCP42010 digipot(Plugin_152_pin[0], Plugin_152_pin[1], Plugin_152_pin[2]);

``` 

but same result. 
pin[0], pin[1], pin[2] are set to GPIO 12, GPIO 14 and GPIO 13 but for example, when this plugin is activate, xx.xx.xx.xx/control?cmd=GPIO,16,0 don't respond

**Comment by TD-er** [comment]
Can you show a bit more of that code you're trying?

Also, I don't know if that MCP42010 library is changing the state of the GPIO pins.
For example it may change a pin to input mode and pull-up enabled, while the plugin handling the command is expecting the pin to be set to output by the init of that plugin.

Apart from that, you're trying to do something which is not meant to be working, since using a GPIO pin for different plugins is for sure never been tested and also not kept in mind when designing a plugin.
And it is really hard to make it all work together for any (unknown) combination of plugins which do not have exclusive access to a given pin.
Only exception on this may be when a pin is being used for some bus like I2C or something similar and both plugins using the same pin are actually only sharing the same bus and thus never addressing the GPIO pin directly.

**Comment by antibill51** [comment]
Each plugin uses separate GPIOs. But once this plugin is activated, I can not control any other GPIO output. NeoPixel candle works well though. All I need to do is disable the MCP42010 plugin so that the GPIOs refit normally.

**Comment by TD-er** [comment]
OK, then I think I misinterpreted the issue you reported.
So no other plugin can work anymore when this one is active?

**Comment by TD-er** [comment]
OK, with that in mind, I looked a bit further in your PLUGIN_WRITE case.
You always do a `success = true;` there, but you should only do it when your plugin served the command.
So you only should assign true if the command matches the one you can successfully handle (and thus handled)

**Comment by antibill51** [comment]
> OK, with that in mind, I looked a bit further in your PLUGIN_WRITE case.
> You always do a `success = true;` there, but you should only do it when your plugin served the command.
> So you only should assign true if the command matches the one you can successfully handle (and thus handled)


I will test immediately ! Thanks

**Comment by antibill51** [comment]
It's working ! 
Thank you so much ! When I think of all this time lost for such a small thing ...

**Comment by TD-er** [comment]
You're still constructing this object, even when none of the commands match
```c++
MCP42010 digipot(Plugin_152_pin[0], Plugin_152_pin[1], Plugin_152_pin[2]);
```
The constructor of that object does set the pin states and does perform a write to a pin.
So you may want to check first  if there is a need for that constructor and then construct it.

For example
```c++
    case PLUGIN_WRITE:
    {
        String command = parseString(string, 1);      
        const bool run_chambre_command = command.equalsIgnoreCase(F("chambre"));
        const bool run_second_command = command.equalsIgnoreCase(F("second"));
        if (run_chambre_command || run_second_command) {
            MCP42010 digipot(Plugin_152_pin[0], Plugin_152_pin[1], Plugin_152_pin[2]);

            if (run_chambre_command)
            {
              int val1;
              val1 = event->Par1;   //Pot1
              Plugin_152_PotDest[0] = val1;
              digipot.setPot(1,val1);
              success = true;
            }

            if (run_second_command)
            {
              int val2;
              val2 = event->Par1;   //Pot2
              Plugin_152_PotDest[1] = val2;
              digipot.setPot(2,val2);
              success = true;
            }       
        }
        break;
    }
```

**Comment by antibill51** [comment]
For this plugin to be usable for others, it would be necessary for example that I can give him a command like: MCP: 0: 255 to get digipot.setPot (0,255)
MCP: 1: 0 to get digipot.setPot (1,0)

**Comment by TD-er** [comment]
That's not really hard to do, you can give up-to 4 or 5 parameters to a command if my memory serves me well.

**Comment by antibill51** [comment]
I try with : 
```
    case PLUGIN_WRITE:
      {
        String tmpString  = string;
          MCP42010 digipot(Plugin_152_pin[0], Plugin_152_pin[1], Plugin_152_pin[2]);

        if (tmpString.startsWith(F("MCP:"))){
          int idx1 = tmpString.indexOf(':');
          int idx2 = tmpString.indexOf(':', idx1+1);
          int idx3 = tmpString.indexOf(':', idx2+1);
          String number_mcp = tmpString.substring(idx1+1, idx2);
          String val_mcp = tmpString.substring(idx2+1, idx3);
          Plugin_152_PotDest[number_mcp] = val_mcp;
          digipot.setPot(number_mcp,val_mcp);
          success = true;
        }


        break;
      }
```

`but  digipot.setPot(number_mcp,val_mcp);` need byte

**Comment by TD-er** [comment]
You're not checking for the returned value of `indexOf`.
If that's a `-1` then the char or string was not found.
Also the strings you get can be converted to int or float.

See the functions I made for this in `Misc.ino` called `validIntFromString` or `validFloatFromString`

**Comment by antibill51** [comment]
it seems to work like this:
```
    case PLUGIN_WRITE:
      {

        String tmpString  = string;
        int argIndex = tmpString.indexOf(',');
        if (argIndex)
          tmpString = tmpString.substring(0, argIndex);

        if (tmpString.equalsIgnoreCase(F("MCP")))
        {
          int pot;
          int value;
          pot = event->Par1;
          value = event->Par2;

          MCP42010 digipot(Plugin_152_pin[0], Plugin_152_pin[1], Plugin_152_pin[2]);
          Plugin_152_PotDest[pot] = value;
          digipot.setPot(pot,value);
          success = true;
        }


        break;
      }

```

Your function will surely be useful later. thank you so much!

**Comment by TD-er** [comment]
Those functions are (very likely) also used to parse the command and fill the Par1...ParN members of the event.

**Comment by TD-er** [comment]
Hmmm, you're now using "MCP" as a command, but wasn't that one already being used for the GPIO port multiplexer plugins?

**Comment by antibill51** [comment]
Argh ! 
What command did you suggest?

**Comment by TD-er** [comment]
Well, you can name it "digpot" ?

**Comment by antibill51** [comment]
Perfect.
It is done

**Comment by TD-er** [comment]
So I guess it can be merged now?

**Comment by antibill51** [comment]
Yes it can!

**Pull request merged**
