### PR TITLE
No Load Firmware on mega version

### PR DESCRIPTION
**Pull request by tonydee2377**
Hi,
why is there no more firmware loading in the mega version?

Thanks

### CODE REVIEW

**Comment by TD-er** [comment]
Can you be a bit more specific?
What is not loading, and what do you want to contribute with this pull request?

**Comment by tonydee2377** [comment]
39323816-09ccc23c-498e-11e8-90a9-b536e7faa79b

**Comment by tonydee2377** [comment]
I'm sorry,
I can't find this button in the mega version

**Comment by TD-er** [comment]
On ESP32, it has been added very very recently.
So I guess it is not yet included in the latest nightly build.

**Comment by tonydee2377** [comment]
yes, but not even esp8266 included.
I speak of the last build of April, it was convenient to release the BIN to update new functions without reprogramming it

**Comment by TD-er** [comment]
It is still present as a feature, for ESP82xx.
Only way when it is disabled is when you flash a sketch which is too large so there is no space left for OTA updates.
This only happens on 1M units when you flash a build without "minimal OTA" in the name.

**Comment by tonydee2377** [comment]
ok I will try again on esp8266 removing some things, I am testing it on all devices and I realized that there was no longer this function, or I will use build 2.0 where this button exists.
I saw the OTA update via Arduino software, but I cannot install software to upgrade the device to an end user.

Thank yuo, for support!

**Pull request closed without merging**
