### PR TITLE
Plugin for Eastron SDM120C Energy Meter

### PR DESCRIPTION
**Pull request by sjfaustino**
Still in development.
Lots to do.

### CODE REVIEW

**Comment by beicnet** [comment]
@sjfaustino Can you please redo this plugin for older ESPEasy version too?

**Comment by sjfaustino** [comment]
I'm starting to use ESPEasy and went with the latest version from github, so no idea on what would be needed for the older version.

I would be happy to add a .bin of the latest version on my fork with this plugin included if someone wants to use it.

**Comment by beicnet** [comment]
@sjfaustino A lot of us using the old builds too, like R120 and R147...

**Comment by yuret** [comment]
sdm
sdm2

**Pull request merged**
