### PR TITLE
Create _P163_DS1631.ino

### PR DESCRIPTION
**Pull request by bisnouk**
Ver 1.0.0 - Plugin state : stable on ESPEasy 2.0.0-dev8
DS1631 is a very chip I2C high precision temperature sensor.
And free sample are available on Dallas web site.

### CODE REVIEW

**Comment by beicnet** [comment]
@bisnouk  Can you make a version for the previous release too?!

**Comment by bisnouk** [comment]
Hi,
I'm rookie on GitHub, 
I added a version line in the description.
I hope that's what you meant.
Regards

**Comment by beicnet** [comment]
Hi,

I meant to be able to work on older versions of ESPEasy (because this will not work).

Regards

**Comment by bisnouk** [comment]
oh.... I don't understand ! 
If I find a little time, I will put the part WEB_FORM_LOAD in R120 format (like this : string += F("<TR><TD>Device Nr:<TD><select name='plugin_163_dev'>");...)

Meanwhile, by fixing the I2C address in the code and the resolution of the temperature measurement and commenting on the non-compatible lines, the plugin must work.

**Comment by beicnet** [comment]
@bisnouk Yes, I meant to be usable with R120 version too.

**Pull request merged**
