### PR TITLE
Programmable SYNC1 and other minor updates

### PR DESCRIPTION
**Pull request by svollebregt**
Various improvements:
- Programmable SYNC1 byte for remote
- Small cosmetic change to interface
- Updates to allow building with recent mega releases (VType)

More info and binaries: https://github.com/svollebregt/ESPEASY_Plugin_ITHO and https://gathering.tweakers.net/forum/view_message/62062116

### CODE REVIEW

**Comment by TD-er** [comment]
Just browsed through the GoT thread and noticed this plugin is being used a lot.
Should we move it to the main repository?

**Comment by svollebregt** [comment]
It has been working reliable with every mega I tested for the past year,  so I would not expect issues when merging it into the main. If any code changes are required I can maintain the plugin as long as I have an Itho device. 

It does cause occasional crashes (~1 time per week) which I think originate from the Itho plugin (my other ESPEasy nodes are rock stable). No clue at the origin of those at the moment.

**Comment by TD-er** [comment]
Those crashes, are they HW or SW watchdog, or an exception?
And if an exception, which one? (nr)

**Comment by svollebregt** [comment]
To be honest I don't recall. At my side it has been running for over 2 weeks without a single crash, hence I think we can conclude the plugin is stable.

**Comment by TD-er** [comment]
Thanks for the update.

**Pull request merged**
