### PR TITLE
Create _P186_Ventus_W266

### PR DESCRIPTION
**Pull request by JustMe-NL**
Plugin to embed a esp into the display unit of a Ventus W266 weather station and sniff the data send by the remote sensor unit. The received data can then be send it to a controller like Domoticz.

### CODE REVIEW

**Comment by chunter1** [comment]
I just installed your plugin and tried to get it work with FHEM.
I discovered the following bugs:

1.) Calculation of wind values is not correct.
It should be something like this:
`
float average = float((Plugin_186_databuffer[11]) * 256 + Plugin_186_databuffer[10]) / 10.0;   // Wind speed average in 10 * m/s
float gust = float((Plugin_186_databuffer[13]) * 256 + Plugin_186_databuffer[12]) / 10.0;      // Wind speed gust in 10 * m/s
`

2.) When using HTTP protocol type (generic or FHEM) the event->sensorType must be defined in every PLUGIN_READ case.
I could get it run using the following:
`
            case (0):
            { ...
              event->sensorType = SENSOR_TYPE_DUAL;
              break;
            }
            case (1):
            {...
              event->sensorType = SENSOR_TYPE_TRIPLE;
              break;
            }
            case (2):
            {...
              event->sensorType = SENSOR_TYPE_DUAL;
              break;
            }          
            case (3):
            {...
              event->sensorType = SENSOR_TYPE_SINGLE;
              break;
            }
            case (4):
            {...
              event->sensorType = SENSOR_TYPE_SINGLE;              
              break;
            }
            case (5): 
            {...
              event->sensorType = SENSOR_TYPE_SINGLE;              
              break;
            }
`

**Comment by JustMe-NL** [comment]
Thank you chunter1. I fixed the multiplication for the wind speeds.

The sensor type however should work. The main ESPEasy.ino sets the sensor type first (in SensorSendTask) from the device type (sensor type single) before reading the plugins. So I only change the type in the plugin_read when it needs to be something else, just like in _P001_Switch.

**Comment by chunter1** [comment]
hi,
is there a special reason why you use the factor "10 x m/s"  for the windspeeds?
wouldn't it be more convenient to pass the values in their original range?

**Comment by JustMe-NL** [comment]
Hi,
Mainly because Domoticz expects the wind speed in 10 * m/s and it is the raw value from the sensor: [https://www.domoticz.com/wiki/Domoticz_API/JSON_URL%27s#Wind](https://www.domoticz.com/wiki/Domoticz_API/JSON_URL%27s#Wind)

**Comment by chunter1** [comment]
ok, i see.
I just noticed that the plugin stopped receiving/accepting data from the W266 after about 160 minutes of uptime.
It is still sending the last data every 10 seconds, but no new data.
The espeasy-log is also not showing any received data from the W266 any more.
After a rebooting espeasy it seems to work again?

By the way... am i right that data is coming in every 30 seconds from the W266?
If yes, wouldn't it be better to use the same interval (30s instead of 10s) in sending the data to the server?

**Comment by JustMe-NL** [comment]
The data is send about every 50 seconds from the sensor unit so received every 50 seconds by the display unit. The ESP Easy framework asks for new data every 30 seconds. If there is new data, we send that, else we send no data (success=false with the latest patches) because otherwise the sensorType gets screwed.

I'm not sure why it sometimes stopped receiving. If seen the same behaviour on the display unit with a test program (without the esp framework)  and a scope attached. The data is queried from the RFM but not received by the display units CPU.

**Comment by chunter1** [comment]
I tried to verify your parameters with my SDR receiver and Oscilloscope.
Data is coming in at intervals of 31..33 seconds.
Carrier frequency is around 869,8 MHz WBFSK.
Would be interresting to get a dump of all registers so we could adapt the JeeLink to the W266 :)
By the way.. i again observed the case that data is normally beeing received and shown in the espeasy log, but it is not sent to the home automation server?
Also the UV index is always showing 0,0?

**Comment by chunter1** [comment]
Hi,
i made a dump of MOSI and MISO aswell.
Can you please explain, why you chose 7F as magic word although it can be found more than one time in the stream?
Wouldn't the sequence "01 7F" make more sense or maybe ignoring the MOSI completeley and only trigger on MISO?

`
83 FF 04 00 86 00 87 01 89 7F F0 20 9D 40 9C 1D A0 A1 A1 20 A2 4E A3 A5 A4 00 A5 13 AA 1E B0 00 B2 00 B3 0A B4 64 B5 20 B6 2D B7 D4 F1 22 F2 60 F3 00 F4 00 F5 73 F6 7B F7 20 88 03 88 00 FE 16 85 10 03 FF 04 00 87 05 87 00 03 FF 04 00 86 00 87 01 89 7F F0 20 9D 40 9C 1D A0 A1 A1 20 A2 4E A3 A5 A4 00 A5 13 AA 1E B0 00 B2 00 B3 0A B4 64 B5 20 B6 2D B7 D4 F1 22 F2 60 F3 00 F4 00 F5 73 F6 7B F7 20 88 03 88 00 FE 16 85 10 03 FF 04 00 87 05 03 FF 04 00 87 01 7F FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF 87 00 03 FF 04 00 86 00 87 01 89 7F F0 20 9D 40 9C 1D A0 A1 A1 20 A2 4E A3 A5 A4 00 A5 13 AA 1E B0 00 B2 00 B3 0A B4 64 B5 20 B6 2D B7 D4 F1 22 F2 60 F3 00 F4 00 F5 73 F6 7B F7 20 88 03 88 00 FE 16 85 10 03 FF 04 00 87 05 87 00 03 FF 04 00 86 00 87 01 89 7F F0 20 9D 40 9C 1D A0 A1 A1 20 A2 4E A3 A5 A4 00 A5 13 AA 1E B0 00 B2 00 B3 0A B4 64 B5 20 B6 2D B7 D4 F1 22 F2 60 F3 00 F4 00 F5 73 F6 7B F7 20 88 03 88 00 FE 16 85 10 03 FF 04 00 87 05 87 00

00 87 01 89 7F F0 20 9D 40 9C 1D A0 A1 A1 20 A2 4E A3 A5 A4 00 A5 13 AA 1E B0 00 B2 00 B3 0A B4 64 B5 20 B6 2D B7 D4 F1 22 F2 60 F3 00 F4 00 F5 73 F6 7B F7 20 88 03 88 00 FE 16 85 10 03 FF 04 00 87 05 87 00 00 00 00 00 00 00 20 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 20 00 02 00 00 00 30 00 82 00 00 00 74 94 1A 34 00 00 34 00 08 00 00 00 00 4D 00 00 00 3F 6A 00 00 2F 00 00 00 20 00 10 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 20 00 12 00 00 00 00 00 20 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 20 00 02 00 00 00 00
`

**Comment by JustMe-NL** [comment]
Hi,

Data is ignored by the plugin if the CRC is incorrect but I'm not sure if that is what you see. the CRC should be 00 and is shown in the log after as "-> XX" after the revived data. Although I have seen cases whereby the data is incorrect but the CRC is correct.

As for the 7F: We check the magic byte per datablock (a datablock being data send while nSel is continually low), so we also check the nSel. Then you'll see the 7F occurs twice but only one datablock has the correct length. Checking on a sequence of 01 7F only complicates things. So to complete your dump and get all settings for the RFM module you need to capture nSel as well.

**Comment by chunter1** [comment]
ok.
since sniffing the SPI interface of the RFM31 receiver inside the W266 is definately unreliable (does not provide any measurements from time to time for 20 minutes or more), i need to find a better working method.
Maybe directly connecting a RFM69 to an ESP32.

**Comment by JustMe-NL** [comment]
That should work. It is actually a RFM31 in a RFM01 pinout.

**Comment by JustMe-NL** [comment]
Please bear in mind that the RFM modules have additional error detection methods and the displaycontroller will only read the databuffer if a frame has been recieved that complies with the protoccols of the reciever module. It polls the RFM and if a "correct" frame has been recieved it reads the databuffer. The databuffer contains the additional CRC. The CRC we see in the data sniffed frothe displayunit is not the same CRC as that used by the RFM modules.

This could explain the behaviour you are seeing.

**Comment by pm-cz** [comment]
Hi, sorry for stepping in, but I use RXB6 ASK/OOK module to receive data from older Ventus sensors/station (Auriol label) and decode it on Arduino. However I did never have time/manage to port in to ESP8266 and moreover the sensitivity is worse when powering it with 3.3V. I wonder if they still use the same protocol.

**Comment by JustMe-NL** [comment]
Unfortunatly not suitable for the Ventusw266 which transmits @868 MHz using gfsk.

**Comment by chunter1** [comment]
Hi JustMe-NL,
i would like to ask if i can take your plugin as basis to write an own plugin that does not use the internal RFM31 but a stand alone RFM69 receiver.
That way we can avoid the problem of periods where nothing is received.

**Comment by JustMe-NL** [comment]
I think the periods are caused by bad reception, especially if your display is not showing any new values as well. That said, a standalone receiver could help with a better antenna.

As far as creating your own plugin, off course! No need to ask for permission. A seperate RFM69 module would be more inline with the ESP Easy project. Maybe, when your plugin is ready, we could integrate the two into one plugin. I had trouble sourcing the RFM31 module so I just ordered a spare display module and saved myself the work of recreating the complete RFM protocol and focussed on reading and decoding just the payload.

**Comment by chunter1** [comment]
Hi JustMe,
i got a first version of my plugin using a RFM69 running and it works well so far.
Using a RFM69 modul opens so much possibilities for receiving different sensors it makes fun ;)
I like the idea of combining our plugins.
In future it would be cool to have a plugin where you can choose from a list of sensors you want to receive or transmit to.
Do you have an email address where i can contact you for some questions concerning the packet data you decoded so far?

**Comment by JustMe-NL** [comment]
Hi Chunter1,

You can reach me at this email address.

**Comment by psy0rz** [comment]
this is already in the main-repo, right?

**Pull request closed without merging**
