### PR TITLE
P170

### PR DESCRIPTION
**Pull request by papperone**
added DEBUG info

### CODE REVIEW

**Comment by psy0rz** [comment]
w00ps you have merge conflicts :(

**Comment by papperone** [comment]
hi Psy0rz, the first request was a mistake and I thought I deleted it...
can youplease help?

**Comment by papperone** [comment]
hi , I updated this pullrequest with a bug fixed as per feedback from the forum, but not sure it's committed correctly, can you please help?

**Comment by psy0rz** [comment]
it seems i can just merge it now?

**Pull request merged**
