### PR TITLE
Added _P147_DMX512.ino

### PR DESCRIPTION
**Pull request by jkDesignDE**
Control DMX512 devices with commnad:
"DMX,5=123,22,33,44"
For more descriptions see header of file.

Status: Working and tested with actual MEGA environment

### CODE REVIEW

**Comment by jkDesignDE** [comment]
@psy0rz : How are the rules to get a plugin from playground to mega? I think some of my plugin could be useful for other people.

**Comment by psy0rz** [comment]
The rule is: If the plugin is generic enough, has clean code, and seems to work, and there are some unknown factors as well. ;)

Also the rule is that it should have at the correct TESTING or DEV ifdefs and texts in the plugin name.

Another rule: We're out of IRAM, so the plugin shouldn't use any extra IRAM.

If you think all is ok, change the plugin number/ifdef/name and then make a pullrequest on the mainrepo.

Edwin

**Comment by psy0rz** [comment]
hmm...maybe i should add these rules somewhere on the wiki :)

**Comment by psy0rz** [comment]
another rule is it should use the new html-functions. (or have an ifdef if you want to make it backwards compatible).

**Comment by psy0rz** [comment]
i just updated the wiki, since it was about time :)

https://www.letscontrolit.com/wiki/index.php/ESPEasyDevelopmentGuidelines

**Pull request merged**
