### PR TITLE
HLW8012 plugin bug fixes and update

### PR DESCRIPTION
**Pull request by papperone**
BugFix: Calibration values were not applied after reboot/restart but only loaded in the GUI. Now it's fixed and reading are correct since the module poweron/restart

### CODE REVIEW

**Comment by papperone** [comment]
can someone merge this? as well can someone explain how a "playground" plugin can be moved as part of the official release? who is in charge of testing/validating such plugins?

**Comment by beicnet** [comment]
@papperone ask @psy0rz

**Comment by papperone** [comment]
@psy0rz can you please merge this PR?
as well what is the process to have a plugin merged in the main repository?

**Comment by papperone** [comment]
is only psy0rz that can merge these requests? it's pending more than 2 weeks now :(

**Comment by papperone** [comment]
SORRY! don't know what happened but the new plugin I wanted to upload was inserted in this previously opened Pull Request; it seems GitHub app on Windows won't let me create a new PU if I do have one still open :(

**Comment by papperone** [comment]
can someone please help? I cannot open any new Pull Request, when I try I get an error "Request Failed / Validation Failed" :(
and if I try to commit only of course the new plugin is added to the current one not yet merged!

**Comment by vitalogy** [comment]
@papperone 
Your work should always be done in a separate local branch, not in the local master branch.

You can try to rename your local master branch to something, like "old-dev" and fetch the remote master into the a new local master. Then you can compare both and create a new local branch for your work. But I don't know exactly the single steps.

**Comment by papperone** [comment]
that's what I try to do and it's always been working in the past but now I got the error above and no clue how to solve it.....

**Comment by psy0rz** [comment]
the wiki explains how to get plugins in the main repo.

**Pull request merged**
