### PR TITLE
Dealing with hidden Extratasksettings related bugs.

### PR DESCRIPTION
**Pull request by enesbcs**

### CODE REVIEW

**Comment by TD-er** [comment]
Do you give a heads-up when it must be merged? ;)

**Comment by enesbcs** [comment]
I finished with testing. Currently everything works to me, as i planned.. however i think user feedbacks and more testers needed. :)

**Comment by TD-er** [comment]
Is it OK if I already merge these?

**Comment by enesbcs** [comment]
i think the are ready to merge

**Pull request merged**
