### PR TITLE
Reworked the code and removed some bugs.

### PR DESCRIPTION
**Pull request by berbergh**
https://github.com/letscontrolit/ESPEasyPluginPlayground/compare/master...berbergh:master#diff-33b54db07a11bbe5202cb7bc7b797c4a

### CODE REVIEW

**Comment by psy0rz** [comment]
uuh how did you create a merge conflict on your own code? :)

**Comment by berbergh** [comment]
Thought I understood what I was doing.
I don’t know what to do nex. Just wanted to upload a newer version.
Can you please remove the .ino?

Thanks.

Verzonden vanuit Mail voor Windows 10

Van: DatuX
Verzonden: maandag 26 februari 2018 23:25
Aan: letscontrolit/ESPEasyPluginPlayground
CC: berbergh; Author
Onderwerp: Re: [letscontrolit/ESPEasyPluginPlayground] Reworked the code andremoved some bugs. (#83)

uuh how did you create a merge conflict on your own code? :)
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.



---
Deze e-mail is gecontroleerd op virussen door AVG.
http://www.avg.com

**Comment by berbergh** [comment]
I first removed the old version from my own repository.
Then I have the new version uploaded to my repository

How can I now get it to letscontrolit/ESPEasyPluginPlayground ?



Verzonden vanuit Mail voor Windows 10

Van: DatuX
Verzonden: maandag 26 februari 2018 23:25
Aan: letscontrolit/ESPEasyPluginPlayground
CC: berbergh; Author
Onderwerp: Re: [letscontrolit/ESPEasyPluginPlayground] Reworked the code andremoved some bugs. (#83)

uuh how did you create a merge conflict on your own code? :)
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.



---
Deze e-mail is gecontroleerd op virussen door AVG.
http://www.avg.com

**Comment by TomSwaro** [comment]
Hi,  my project with  AdafruitSI1145 sensor works well now since 2 days.
Only one issue with MQTT Controllers I found:
MQTT reported only the first value ( VISIBLE )
I changed the SENSOR_TYPE... , now Controller Plugin 002 formats the MQTT with all 3 values.

286         Device[deviceCount].VType = SENSOR_TYPE_SINGLE;
new         Device[deviceCount].VType = SENSOR_TYPE_TRIPLE;

https://github.com/letscontrolit/ESPEasyPluginPlayground/blob/edc75ea5991243d5360fd68ffb96947e375fd54c/_P113_SI1145.ino#L286

**Pull request closed without merging**
